## Imports

In [1]:
import numpy as np
import pandas as pd
import requests
import time

pd.set_option("display.max_rows", 200) # Set the maximum number of rows to display
pd.set_option("display.width", 120) # Set the width of the display


## Étape 1 — Liste des maladies GBD niveau 3

In [2]:
# Liste curatée de maladies GBD niveau 3, par catégorie parente (niveau 2) ---
# Sources : hiérarchie des causes GBD 2019/2021 (structure publique, cf. publications GBD /
# documentation IHME). Liste non exhaustive.

raw_data = {
    "Neurological disorders": [
        "Alzheimer's disease and other dementias",
        "Parkinson's disease",
        "Epilepsy",
        "Multiple sclerosis",
        "Motor neuron disease",
        "Migraine",
        "Tension-type headache",
        "Guillain-Barré syndrome",
        "Encephalitis",
        "Idiopathic developmental intellectual disability",
        "Headache disorders",
        "Tension-type headache",
    ],
    "Cardiovascular diseases": [
        "Ischemic heart disease",
        "Ischemic stroke",
        "Intracerebral hemorrhage",
        "Subarachnoid hemorrhage",
        "Hypertensive heart disease",
        "Cardiomyopathy and myocarditis",
        "Atrial fibrillation and flutter",
        "Rheumatic heart disease",
        "Aortic aneurysm",
        "Peripheral artery disease",
        "Endocarditis",
        "Non-rheumatic valvular heart disease",
    ],
    "Neoplasms": [
        "Breast cancer",
        "Prostate cancer",
        "Colon and rectum cancer",
        "Tracheal, bronchus, and lung cancer",
        "Ovarian cancer",
        "Cervical cancer",
        "Uterine cancer",
        "Liver cancer",
        "Stomach cancer",
        "Esophageal cancer",
        "Pancreatic cancer",
        "Non-Hodgkin lymphoma",
        "Leukemia",
        "Brain cancer",
        "Bladder cancer",
        "Kidney cancer",
        "Thyroid cancer",
        "Malignant skin melanoma",
        "Larynx cancer",
        "Multiple myeloma",
    ],
    "Endocrine, metabolic, blood and immune disorders": [
        "Diabetes mellitus type 1",
        "Diabetes mellitus type 2",
        "Gout",
        "Thyroid disorders",
        "Systemic lupus erythematosus",
        "Sickle cell disorders",
        "Thalassemias",
        "G6PD deficiency",
        "Addison's disease",
        "Other endocrine, metabolic, blood, and immune disorders",
    ],
    "Musculoskeletal disorders": [
        "Rheumatoid arthritis",
        "Osteoarthritis",
        "Low back pain",
        "Neck pain",
        "Gout (musculoskeletal manifestations)",
        "Juvenile idiopathic arthritis",
        "Fibromyalgia",
        "Other musculoskeletal disorders",
    ],
    "Mental disorders": [
        "Depressive disorders",
        "Anxiety disorders",
        "Bipolar disorder",
        "Schizophrenia",
        "Eating disorders",
        "Autism spectrum disorders",
        "Attention-deficit/hyperactivity disorder",
        "Conduct disorder",
        "Post-traumatic stress disorder",
        "Obsessive-compulsive disorder",
    ],
    "Chronic respiratory diseases": [
        "Chronic obstructive pulmonary disease",
        "Asthma",
        "Interstitial lung disease",
        "Pulmonary sarcoidosis"
        
    ],
    "Digestive diseases": [
        "Cirrhosis and other chronic liver diseases",
        "Gastritis and duodenitis",
        "Peptic ulcer disease",
        "Inflammatory bowel disease",
        "Pancreatitis",
        "Gallbladder and biliary diseases",
        "Appendicitis",
        "Vascular intestinal disorders",
        "Irritable bowel syndrome",
    ],
    "Skin and subcutaneous diseases": [
        "Dermatitis",
        "Psoriasis",
        "Acne vulgaris",
        "Alopecia areata",
        "Urticaria",
        "Scabies",
        "Fungal skin diseases",
        "Decubitus ulcer",
        "Other skin and subcutaneous diseases",
    ],
    "Sense organ diseases": [
        "Age-related and other hearing loss",
        "Cataract",
        "Glaucoma",
        "Age-related macular degeneration",
        "Refraction disorders",
        "Other vision loss",
    ],
    "Urinary, gynecological and reproductive diseases": [
        "Urinary tract infections",
        "Urolithiasis",
        "Benign prostatic hyperplasia",
        "Male infertility",
        "Interstitial nephritis",
        "Endometriosis",
        "Uterine fibroids",
        "Genital prolapse",
        "Premenstrual syndrome",
        "Female infertility",
        "Polycystic ovary syndrome",
    ],
}

rows = []
for category, diseases_list in raw_data.items():
    for name in diseases_list:
        rows.append({
            "cause_name": name,
            "parent": category,
        })

diseases = pd.DataFrame(rows)
diseases

                                            cause_name                                            parent
0              Alzheimer's disease and other dementias                            Neurological disorders
1                                  Parkinson's disease                            Neurological disorders
2                                             Epilepsy                            Neurological disorders
3                                   Multiple sclerosis                            Neurological disorders
4                                 Motor neuron disease                            Neurological disorders
5                                             Migraine                            Neurological disorders
6                                Tension-type headache                            Neurological disorders
7                              Guillain-Barré syndrome                            Neurological disorders
8                                         Encephalitis                            Neurological disorders
9     Idiopathic developmental intellectual disability                            Neurological disorders
10                                  Headache disorders                            Neurological disorders
11                               Tension-type headache                            Neurological disorders
12                              Ischemic heart disease                           Cardiovascular diseases
13                                     Ischemic stroke                           Cardiovascular diseases
14                            Intracerebral hemorrhage                           Cardiovascular diseases
15                             Subarachnoid hemorrhage                           Cardiovascular diseases
16                          Hypertensive heart disease                           Cardiovascular diseases
17                      Cardiomyopathy and myocarditis                           Cardiovascular diseases
18                     Atrial fibrillation and flutter                           Cardiovascular diseases
19                             Rheumatic heart disease                           Cardiovascular diseases
20                                     Aortic aneurysm                           Cardiovascular diseases
21                           Peripheral artery disease                           Cardiovascular diseases
22                                        Endocarditis                           Cardiovascular diseases
23                Non-rheumatic valvular heart disease                           Cardiovascular diseases
24                                       Breast cancer                                         Neoplasms
25                                     Prostate cancer                                         Neoplasms
26                             Colon and rectum cancer                                         Neoplasms
27                 Tracheal, bronchus, and lung cancer                                         Neoplasms
28                                      Ovarian cancer                                         Neoplasms
29                                     Cervical cancer                                         Neoplasms
30                                      Uterine cancer                                         Neoplasms
31                                        Liver cancer                                         Neoplasms
32                                      Stomach cancer                                         Neoplasms
33                                   Esophageal cancer                                         Neoplasms
34                                   Pancreatic cancer                                         Neoplasms
35                                Non-Hodgkin lymphoma                                         Neoplasms
36                                            Leukemia                                         Neoplasms
37                                        Brain cancer                                         Neoplasms
38                                      Bladder cancer                                         Neoplasms
39                                       Kidney cancer                                         Neoplasms
40                                      Thyroid cancer                                         Neoplasms
41                             Malignant skin melanoma                                         Neoplasms
42                                       Larynx cancer                                         Neoplasms
43                                    Multiple myeloma                                         Neoplasms
44                            Diabetes mellitus type 1  Endocrine, metabolic, blood and immune disorders
45                            Diabetes mellitus type 2  Endocrine, metabolic, blood and immune disorders
46                                                Gout  Endocrine, metabolic, blood and immune disorders
47                                   Thyroid disorders  Endocrine, metabolic, blood and immune disorders
48                        Systemic lupus erythematosus  Endocrine, metabolic, blood and immune disorders
49                               Sickle cell disorders  Endocrine, metabolic, blood and immune disorders
50                                        Thalassemias  Endocrine, metabolic, blood and immune disorders
51                                     G6PD deficiency  Endocrine, metabolic, blood and immune disorders
52                                   Addison's disease  Endocrine, metabolic, blood and immune disorders
53   Other endocrine, metabolic, blood, and immune ...  Endocrine, metabolic, blood and immune disorders
54                                Rheumatoid arthritis                         Musculoskeletal disorders
55                                      Osteoarthritis                         Musculoskeletal disorders
56                                       Low back pain                         Musculoskeletal disorders
57                                           Neck pain                         Musculoskeletal disorders
58               Gout (musculoskeletal manifestations)                         Musculoskeletal disorders
59                       Juvenile idiopathic arthritis                         Musculoskeletal disorders
60                                        Fibromyalgia                         Musculoskeletal disorders
61                     Other musculoskeletal disorders                         Musculoskeletal disorders
62                                Depressive disorders                                  Mental disorders
63                                   Anxiety disorders                                  Mental disorders
64                                    Bipolar disorder                                  Mental disorders
65                                       Schizophrenia                                  Mental disorders
66                                    Eating disorders                                  Mental disorders
67                           Autism spectrum disorders                                  Mental disorders
68            Attention-deficit/hyperactivity disorder                                  Mental disorders
69                                    Conduct disorder                                  Mental disorders
70                      Post-traumatic stress disorder                                  Mental disorders
71                       Obsessive-compulsive disorder                                  Mental disorders
72               Chronic obstructive pulmonary disease                      Chronic respiratory diseases
73                                              Asthma                      Chronic respiratory diseases
74                           Interstitial lung disease                      Chronic respiratory diseases
75                               Pulmonary sarcoidosis                      Chronic respiratory diseases
76          Cirrhosis and other chronic liver diseases                                Digestive diseases
77                            Gastritis and duodenitis                                Digestive diseases
78                                Peptic ulcer disease                                Digestive diseases
79                          Inflammatory bowel disease                                Digestive diseases
80                                        Pancreatitis                                Digestive diseases
81                    Gallbladder and biliary diseases                                Digestive diseases
82                                        Appendicitis                                Digestive diseases
83                       Vascular intestinal disorders                                Digestive diseases
84                            Irritable bowel syndrome                                Digestive diseases
85                                          Dermatitis                    Skin and subcutaneous diseases
86                                           Psoriasis                    Skin and subcutaneous diseases
87                                       Acne vulgaris                    Skin and subcutaneous diseases
88                                     Alopecia areata                    Skin and subcutaneous diseases
89                                           Urticaria                    Skin and subcutaneous diseases
90                                             Scabies                    Skin and subcutaneous diseases
91                                Fungal skin diseases                    Skin and subcutaneous diseases
92                                     Decubitus ulcer                    Skin and subcutaneous diseases
93                Other skin and subcutaneous diseases                    Skin and subcutaneous diseases
94                  Age-related and other hearing loss                              Sense organ diseases
95                                            Cataract                              Sense organ diseases
96                                            Glaucoma                              Sense organ diseases
97                    Age-related macular degeneration                              Sense organ diseases
98                                Refraction disorders                              Sense organ diseases
99                                   Other vision loss                              Sense organ diseases
100                           Urinary tract infections  Urinary, gynecological and reproductive diseases
101                                       Urolithiasis  Urinary, gynecological and reproductive diseases
102                       Benign prostatic hyperplasia  Urinary, gynecological and reproductive diseases
103                                   Male infertility  Urinary, gynecological and reproductive diseases
104                             Interstitial nephritis  Urinary, gynecological and reproductive diseases
105                                      Endometriosis  Urinary, gynecological and reproductive diseases
106                                   Uterine fibroids  Urinary, gynecological and reproductive diseases
107                                   Genital prolapse  Urinary, gynecological and reproductive diseases
108                              Premenstrual syndrome  Urinary, gynecological and reproductive diseases
109                                 Female infertility  Urinary, gynecological and reproductive diseases
110                          Polycystic ovary syndrome  Urinary, gynecological and reproductive diseases

## Étape 2 — Enrichissement automatique : nombre de publications scientifiques

Parmi les variables listées plus haut, le **nombre de publications** est la seule qu'on peut
récupérer entièrement automatiquement, via deux API gratuites et sans clé :

**PubMed / NCBI E-utilities** : `esearch.fcgi` renvoie un simple compte de résultats pour une
  requête donnée.

Les autres variables (proportion de femmes atteintes, financement, délai diagnostique) ne sont
**pas** automatisables de façon fiable — elles nécessitent une recherche ciblée par maladie. On
crée donc des colonnes vides pour elles, à remplir manuellement grâce à une recherche via perplexity sur des sites tels que ameli, gbd, WHO, ...

In [4]:
def count_pubmed(query: str, retries: int = 2, timeout: int = 10) -> float:
    """Retourne le nombre de résultats PubMed pour une requête, ou NaN en cas d'échec."""
    url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
    params = {"db": "pubmed", "term": query, "retmode": "json"}
    for attempt in range(retries):
        try:
            r = requests.get(url, params=params, timeout=timeout)
            r.raise_for_status()
            return int(r.json()["esearchresult"]["count"])
        except Exception:
            time.sleep(1)
    return np.nan

pubmed_counts = []
for disease in diseases["cause_name"]:
    pubmed_counts.append(count_pubmed(disease))
    time.sleep(0.34)  # reste sous la limite de ~3 requêtes/seconde sans clé API NCBI

diseases["publications_pubmed"] = pubmed_counts

n_echecs = sum(1 for count in pubmed_counts if pd.isna(count))
if n_echecs == len(diseases):
    print("Toutes les requêtes ont échoué : le réseau semble bloqué dans cet environnement. ")
else:
    print(f"Publications récupérées pour {len(diseases) - n_echecs}/{len(diseases)} maladies.")

pubmed_df = diseases[["cause_name", "parent", "publications_pubmed"]] \
    .sort_values("publications_pubmed", ascending=False)

pubmed_df

Publications récupérées pour 111/111 maladies.

,cause_name,parent,publications_pubmed
12,Ischemic heart disease,Cardiovascular diseases,618602
24,Breast cancer,Neoplasms,587604
80,Pancreatitis,Digestive diseases,466772
36,Leukemia,Neoplasms,403365
31,Liver cancer,Neoplasms,377782
37,Brain cancer,Neoplasms,293028
73,Asthma,Chronic respiratory diseases,244204
25,Prostate cancer,Neoplasms,241448
45,Diabetes mellitus type 2,"Endocrine, metabolic, blood and immune disorders",233523
2,Epilepsy,Neurological disorders,205751
63,Anxiety disorders,Mental disorders,205258
47,Thyroid disorders,"Endocrine, metabolic, blood and immune disorders",201804
62,Depressive disorders,Mental disorders,200260
54,Rheumatoid arthritis,Musculoskeletal disorders,187981
65,Schizophrenia,Mental disorders,181152
30,Uterine cancer,Neoplasms,179167
1,Parkinson's disease,Neurological disorders,173429
39,Kidney cancer,Neoplasms,169307
61,Other musculoskeletal disorders,Musculoskeletal disorders,168826
34,Pancreatic cancer,Neoplasms,166148
16,Hypertensive heart disease,Cardiovascular diseases,162230
28,Ovarian cancer,Neoplasms,158440
85,Dermatitis,Skin and subcutaneous diseases,156659
79,Inflammatory bowel disease,Digestive diseases,153377
32,Stomach cancer,Neoplasms,150456
29,Cervical cancer,Neoplasms,145980
35,Non-Hodgkin lymphoma,Neoplasms,142792
55,Osteoarthritis,Musculoskeletal disorders,140827
13,Ischemic stroke,Cardiovascular diseases,138228
3,Multiple sclerosis,Neurological disorders,128002
72,Chronic obstructive pulmonary disease,Chronic respiratory diseases,114639
40,Thyroid cancer,Neoplasms,114199
74,Interstitial lung disease,Chronic respiratory diseases,111391
38,Bladder cancer,Neoplasms,110858
44,Diabetes mellitus type 1,"Endocrine, metabolic, blood and immune disorders",100634
95,Cataract,Sense organ diseases,96313
96,Glaucoma,Sense organ diseases,95928
48,Systemic lupus erythematosus,"Endocrine, metabolic, blood and immune disorders",94695
33,Esophageal cancer,Neoplasms,93268
78,Peptic ulcer disease,Digestive diseases,91913
20,Aortic aneurysm,Cardiovascular diseases,86992
8,Encephalitis,Neurological disorders,86045
14,Intracerebral hemorrhage,Cardiovascular diseases,85148
109,Female infertility,"Urinary, gynecological and reproductive diseases",82026
100,Urinary tract infections,"Urinary, gynecological and reproductive diseases",78044
86,Psoriasis,Skin and subcutaneous diseases,75720
67,Autism spectrum disorders,Mental disorders,75640
43,Multiple myeloma,Neoplasms,71855
64,Bipolar disorder,Mental disorders,68958
41,Malignant skin melanoma,Neoplasms,66033
103,Male infertility,"Urinary, gynecological and reproductive diseases",65178
66,Eating disorders,Mental disorders,63018
70,Post-traumatic stress disorder,Mental disorders,60549
10,Headache disorders,Neurological disorders,60220
21,Peripheral artery disease,Cardiovascular diseases,57781
56,Low back pain,Musculoskeletal disorders,57631
5,Migraine,Neurological disorders,55308
68,Attention-deficit/hyperactivity disorder,Mental disorders,54258
22,Endocarditis,Cardiovascular diseases,50766
101,Urolithiasis,"Urinary, gynecological and reproductive diseases",49923
97,Age-related macular degeneration,Sense organ diseases,49410
57,Neck pain,Musculoskeletal disorders,48776
4,Motor neuron disease,Neurological disorders,47642
42,Larynx cancer,Neoplasms,41966
15,Subarachnoid hemorrhage,Cardiovascular diseases,41620
105,Endometriosis,"Urinary, gynecological and reproductive diseases",40741
0,Alzheimer's disease and other dementias,Neurological disorders,37561
26,Colon and rectum cancer,Neoplasms,36998
50,Thalassemias,"Endocrine, metabolic, blood and immune disorders",35691
91,Fungal skin diseases,Skin and subcutaneous diseases,35055
83,Vascular intestinal disorders,Digestive diseases,34650
102,Benign prostatic hyperplasia,"Urinary, gynecological and reproductive diseases",34169
49,Sickle cell disorders,"Endocrine, metabolic, blood and immune disorders",32368
82,Appendicitis,Digestive diseases,31614
106,Uterine fibroids,"Urinary, gynecological and reproductive diseases",31036
89,Urticaria,Skin and subcutaneous diseases,29857
81,Gallbladder and biliary diseases,Digestive diseases,29729
71,Obsessive-compulsive disorder,Mental disorders,28404
110,Polycystic ovary syndrome,"Urinary, gynecological and reproductive diseases",28253
46,Gout,"Endocrine, metabolic, blood and immune disorders",26061
104,Interstitial nephritis,"Urinary, gynecological and reproductive diseases",25591
92,Decubitus ulcer,Skin and subcutaneous diseases,22960
17,Cardiomyopathy and myocarditis,Cardiovascular diseases,22188
84,Irritable bowel syndrome,Digestive diseases,21085
19,Rheumatic heart disease,Cardiovascular diseases,19536
69,Conduct disorder,Mental disorders,18702
59,Juvenile idiopathic arthritis,Musculoskeletal disorders,18117
99,Other vision loss,Sense organ diseases,17894
87,Acne vulgaris,Skin and subcutaneous diseases,17033
60,Fibromyalgia,Musculoskeletal disorders,16889
7,Guillain-Barré syndrome,Neurological disorders,14619
98,Refraction disorders,Sense organ diseases,12588
75,Pulmonary sarcoidosis,Chronic respiratory diseases,11904
76,Cirrhosis and other chronic liver diseases,Digestive diseases,10403
18,Atrial fibrillation and flutter,Cardiovascular diseases,8443
88,Alopecia areata,Skin and subcutaneous diseases,7776
51,G6PD deficiency,"Endocrine, metabolic, blood and immune disorders",7255
52,Addison's disease,"Endocrine, metabolic, blood and immune disorders",7124
107,Genital prolapse,"Urinary, gynecological and reproductive diseases",6803
77,Gastritis and duodenitis,Digestive diseases,6452
90,Scabies,Skin and subcutaneous diseases,6114
108,Premenstrual syndrome,"Urinary, gynecological and reproductive diseases",5855
6,Tension-type headache,Neurological disorders,4945
11,Tension-type headache,Neurological disorders,4945
93,Other skin and subcutaneous diseases,Skin and subcutaneous diseases,2522
53,"Other endocrine, metabolic, blood, and immune ...","Endocrine, metabolic, blood and immune disorders",1964
27,"Tracheal, bronchus, and lung cancer",Neoplasms,1733
94,Age-related and other hearing loss,Sense organ diseases,625
9,Idiopathic developmental intellectual disability,Neurological disorders,246
23,Non-rheumatic valvular heart disease,Cardiovascular diseases,226
58,Gout (musculoskeletal manifestations),Musculoskeletal disorders,76